---
title: "Replication of Study 2 by Kacperczyk & Younkin (2021, Organization Science)"
author: "Seyeon Kim (seyeonk@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

|    I am interested in studying the career processes of entrepreneurs, especially those who move in and out of traditional, hierarchical firms. Kacperczyk and Younkin (2021) found that having an entrepreneurial experience negatively influences workers' prospects at the hiring stage and shows how this founding penalty varies by gender. Study 1 is a resume-based audit study that tested the effect of entrepreneurial experience on the probability of interview callbacks, and Study 2 is an experimental survey that attempted to evaluate the explanations about why there exists a penalty for ex-founders returning to wage employment. I replicate the findings from Study 2, because it is not only appropriate in scope and time but also engages with the literature on understanding why founding penalties exist.

|    Participants are given one of four resumes differing in founding experience and gender and asked to evaluate the given job candidate's qualities, especially their fit and commitment. In other words, this survey experiment is a two-by-two between-subject design with participants randomly assigned to read one type of resume out of four conditions: female founder, male founder, female non-founder/employee, and male employee. The dependent variable is the respondents' willingness to recommend the given job candidate to a future employer, and mediating variables are the extent to which the given job candidate is a good fit to a hierarchical organization and is likely to quit next job. At the end of the experiment, to control for the respondents' characteristics, their information including age, gender, and years of work experience will be collected.  

|    I do want to ask additional questions to the survey experiment that were not included in the original study.  Right after the participants make evaluations about a given job candidate, I would like them to list all reasons why they would or would not want to recommend this person to a future employer. This is because I worry only asking them about fit and commitment like in the original study might yield limited insights into how the employers make decisions in that we lose information on other dimensions such as capability and failure bias that might be as important as fit and commitment when evaluating candidates. 

|    The primary challenge will be to find a sample as similar as possible to the original study: marketing managers with more than five years of work experience and at least a bachelor's degree who come from a diverse range of industries, including manufacturing, advertising, healthcare, software development, and consulting. Because the paper does not mention the industry composition of the sample and only writes that the sample is from "across a range of industries, such as manufacturing, advertising, healthcare, software development, and consulting", I am worried about getting a sample whose industry composition vastly differs from that of the original study sample. Another challenge will be difficulties associated with retaining attention, which would especially increase from my additional questions. The more questions and tasks respondents are asked to do, the more likely that the responses we get are answered less carefully.

|   The link to the repository is as follows: https://github.com/psych251/Kacperczyk2021.git 



